### ISSUE TITLE
Documentation: set-timezone json example breaks UWP

### ISSUE THREAD

**Issue by sepple-ms** [ms-iot/iot-core-azure-dm-client#126]
The documentation JSON sample needs to be updated for timezone settings of desired properties otherwise UWP shuts down (due to nullref):

 "microsoft" : {
        "management" : {
          "timeInfo": {
            "timeZoneDaylightBias": -60,
            "timeZoneDaylightDate": "3/2/2016 2:00:00 AM",
            "timeZoneDaylightName": "Pacific Daylight Time",
            "timeZoneStandardBias": 0,
            "timeZoneStandardDate": "11/1/2016 2:00:00 AM",
            "timeZoneStandardName": "Pacific Standard Time",
            "timeZoneBias": 480,
            "ntpServer": "time.windows.com",
**"timeZoneStandardDayOfWeek": 1,
"timeZoneDaylightDayOfWeek": 1**
          }
        }
    }

**Comment by IoTGirl** [comment]
Hi @sepple-ms 
Can you submit a code change against the doc for review rather than just a text issue? 
Sincerely,
IoTGirl

**Comment by DennisSc** [comment]
Strange. The following is working fine for me, without timeZoneStandard-anything:

![image](https://user-images.githubusercontent.com/11349712/27742011-5feb288e-5db7-11e7-8747-7c7edc2c3a92.png)

**Comment by IoTGirl** [comment]
Closing for submission of code change request
