### ISSUE TITLE
device loses connection

### ISSUE THREAD

**Issue by DennisSc** [ms-iot/iot-core-azure-dm-client#130]
Hi,

I think I need some support... I've set up the IoTDMbackground example and it is working fine... for some time but not reliable. Connection is "lost" after some days, the SystemConfigurator and IoTDMbackground processes are still running and the service state of SystemConfigurator is still "running" when connection is lost.

The device doesn't respond to device twin updates any more, and "device explorer" and the azure iot hub dashboard both say the my device is not connected. When I restart the IoTDMbackground app, the connection is re-established and things start working again, for some time, then same issue again.

Besides from running iotdmbackground in debug mode for several days with VS debugger attached: what else could I do to narrow down the cause? Implement failover behavior inside IoTDMbackground? (How?)

best regards

**Comment by IoTGirl** [comment]
Hi Dennis,
What device and version are you using?
Sincerely,
IoTGirl

**Comment by DennisSc** [comment]
Hi,

I am using "Windows 10 IoT Core v.10.0.15063.414" on a Raspberry Pi B3 with 32GB Samsung Evo SD card, and trying to get the IoTDMbackground from the current master branch to work reliably.
I have switched off Wifi and Bluetooth, and am only using wired ethernet (static IPV4).

Also running a "headed" UWP foreground app (containing a webserver and a mqtt broker) on the same device pretty reliably. The headed app is generally working fine, even after IoTDMbackground loses connection.

If I should test something just let me know.

best regards

**Comment by IoTGirl** [comment]
Hi Dennis,

Only one process can have an Azure connection at a time so may I ask if you have both a foreground and background task/app that are both trying to connect?  Does your design isolate the connection such that there is only one?
Sincerely,
IoTGirl

**Comment by gmileka** [comment]
Hi Dennis,

Do you know if the device lost network connectivity at any point after the initial connection?

Either way, we will take a close look at what is happening and how to best handle such scenarios.

thank you,
George Mileka

**Comment by DennisSc** [comment]
No, sorry - I don't know if connection was interrupted at some time (but needless to say, IoT devices should be expected to sometimes lose their network connection, right?).

The error has not occured again since last restart of IoTDMbackground (5 days ago).
I have now added a notification in azure, to be informed in case it happens again,
![image](https://user-images.githubusercontent.com/11349712/27833627-ebd209f2-60d3-11e7-8ba0-2ed6fa2520a0.png)

I will keep you updated.
regards

**Comment by DennisSc** [comment]
It has happened again, device currently not connected to azure any more, and the network adapter is online since last reboot 9 days ago:

![image](https://user-images.githubusercontent.com/11349712/27841618-603cc280-6103-11e7-85e2-948c5c1ed14f.png)

anything I could check at this point?

regards

**Comment by bfjelds** [comment]
The Azure SDK has added a callback to handle connection changes (in version 1.3.0 of the Microsoft.Azure.Devices.Client).  

We are in the process of adding this to our implementation now.  

In the meantime, you can get this new functionality by updating your project.json (your app and IotDMClientLib) to point at:
```
"Microsoft.Azure.Devices.Client": "1.3.0",
"Microsoft.Extensions.Logging": "1.1.1",
"Microsoft.Extensions.Logging.Abstractions": "1.1.1",
```

Then change the code that constructs the DeviceClient to handle the  connection changes:

```
DeviceClient deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportType.Mqtt);
deviceClient.SetConnectionStatusChangesHandler(async (ConnectionStatus status, ConnectionStatusChangeReason reason) => {
switch (reason)
{
    case ConnectionStatusChangeReason.Bad_Credential: /* handle */ break;
    case ConnectionStatusChangeReason.Client_Close: /* handle */ break;
    case ConnectionStatusChangeReason.Communication_Error: /* handle */ break;
    case ConnectionStatusChangeReason.Connection_Ok: /* handle */ break;
    case ConnectionStatusChangeReason.Device_Disabled: /* handle */ break;
    case ConnectionStatusChangeReason.Expired_SAS_Token: /* handle */ break;
    case ConnectionStatusChangeReason.No_Network: /* handle */ break;
    case ConnectionStatusChangeReason.Retry_Expired: /* handle */ break;
    default: break;
} } );
```

**Comment by DennisSc** [comment]
Thanks a lot! I will try this and let you know.

**Comment by gmileka** [comment]
Hi Dennis, please, let us know if this did not fix the issue. We have also added code to the develop branch which will make sure to recover from lost connectivity.
