### ISSUE TITLE
Add Links to the Samples page 

### ISSUE THREAD

**Issue by atooie** [ms-iot/iot-core-azure-dm-client#191]
iot-core-azure-dm-client/docs/samples.md 

Under Running the Samples, for the bolded sections, suggest adding links.
Example:
- Setup your Azure IoTHub account   <-- include a link to the Azure website that shows how to create an IoT Hub
- Install Visual Studio 2015 Update 3 <-- is this out of date .. should it be a link to where to download latest Visual Studio?
- Setup your IoT Core device using IoT Dashboard <-- include a link to where to downtown IoT Dashboard

**Comment by gmileka** [comment]
Thx for the suggestions... agreed. I've fixed the docs with 3c28fb95893ca89b5ca9762801494511c48deb50.
