### ISSUE TITLE
Exception in HandleGetWindowsTelemetry prevents TwinProps to be reported

### ISSUE THREAD

**Issue by sepple-ms** [ms-iot/iot-core-azure-dm-client#205]
WindowsTelemetry fails with Exception error code: -1610579711 if the following key is not present, preventing DeviceTwinProperties getting reported.

HandleGetWindowsTelemetry
WindowsTelemetry::Get
Exception error code: -1610579711

reg.exe ADD "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0

**Comment by gmileka** [comment]
Fixed the code to continue after the exception (3d79f12f35d54d90d57efff29f1346e7c7ef7593). I've also included a text error message with the exception for easier diagnosis.

We intentionally throw the exception if the user setting for Windows telemetry is not defined.
