### ISSUE TITLE
Can't find samples\Toaster\ConnectionStringProvider.cs

### ISSUE THREAD

**Issue by TerrenceHenry** [ms-iot/iot-core-azure-dm-client#215]
In the documentation, Running the Samples, Step 4 says 

> _Update samples\Toaster\ConnectionStringProvider.cs to use appropriate IotHub device connection string._

But the file ConnectionStringProvider.cs does not exist.

**Comment by gmileka** [comment]
Thank you for pointing this out. This part of the document is outdated.  I've just updated the docs.
