### ISSUE TITLE
Error when Building System Configurator

### ISSUE THREAD

**Issue by cmassman** [ms-iot/iot-core-azure-dm-client#218]
Cannot open include file: 'tlhelp32.h' : No such file or Directory    Impersonator.cpp
Cannot open include file: 'Shlobl.h' : No such file or Directory      Utils.cpp

**Comment by gmileka** [comment]
Hi cmassman,

Which Visual Studio version are you using?
Do you have the C++ toolset installed?

You will need to have the win32 and UWP C++ SDKs installed for the solution to build successfully.

**Comment by cmassman** [comment]
Visual Studio Pro 2017 15.4.4
C++ toolset must be  installed already. because 2 projects build without issues.

Successfully Built Projects: DMMessage,SystemConfigurationProxyInterface.
Projects that fail: ServiceConfigurationProxyClientLib, SystemConfigurator.

You mentioned "win32 and UWP C++ SDKs".  Do I need additional  SDK's installed other than winsdk 10.0.15063.0 ?

I searched the projects for those two header files, but did not find them  tlhelp32.h, Shlobl.h

Thanks for your help!

**Comment by gmileka** [comment]
Correct - the Windows SDK is split in a number of components and not all of them are installed by default.

If you run the  'Visual Studio Installer', and then select the 'Individual components' tab, you can see the detailed list of what is getting installed.

Under 'SDKs, libraries, and frameworks', the following are relevant to the building the solution:
- Windows 10 SDK (version) for UWP: C++
- Windows 10 SDK (version) for Desktop C++ [x86 and x64]
- Windows 10 SDK (version) for Desktop C++ [ARM and ARM64]

So, let's make sure those are installed and give it another try.

For the missing headers, 
- For tlhelp32.h, this seems to be part of the universal SDK, it's installed on my machine at:
c:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\TlHelp32.h This means that installing the UWP SDK should solve the problem.

- For Shlobl.h, I can't find where it's referenced. Utils.cpp does not reference it directly - so it must be coming through one of the headers it is including. Before digging further, let's make sure the SDKs (above) are installed and this error should go away...

**Comment by cmassman** [comment]
Thank you for the clear instructions.   
I was able to load those other SDK's and now it is Building.

Thanks!
