### ISSUE TITLE
Solutions fails to build C++ 17 because of std::tr2::sys deprecation errors

### ISSUE THREAD

**Issue by bderuijsscher** [ms-iot/iot-core-azure-dm-client#226]
The project fails to build because of deprecation errors for the std::tr2::sys library used in src\SharedUtilities\Logger.cpp.:

`warning STL4018: The non-Standard std::tr2::sys namespace is deprecated and will be REMOVED. It is superseded by std::experimental::filesystem. You can define _SILENCE_TR2_SYS_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning.`

Modifying the using directive in the mentioned file to std::experimental::filesystem appears to solve the issue.

(The changes are outlined in the C++17 release notes https://blogs.msdn.microsoft.com/vcblog/2017/12/08/c17-feature-removals-and-deprecations/ )

**Comment by gmileka** [comment]
Thank you for point this out!
We've fixed it with de3333bd00d8e67831fa66931a5828c48061c8c4.
