### ISSUE TITLE
Azure Blob storage (sub)folders not supported when distributing Appx packages

### ISSUE THREAD

**Issue by bderuijsscher** [ms-iot/iot-core-azure-dm-client#227]
When distributing appx packages through Azure Blob storage, the implementation currently expects all files to be located within the root of the specified container. Folders or subfolders within this implementation are not supported and will yield an "container name is missing in " error.

Root cause is het AzureBlobFileTransfer class that implements the BlobInfoFromSource method. This method expects the input string to have exactly one slash, wheras an input string containing one or more subfolders might have two or more.

**Comment by gmileka** [comment]
Thank you! We've checked-in a fix c8b4fed80cab83b3ef395a227cb89dee59d8ae1c.
