### ISSUE TITLE
Discrepancy in integration of SystemConfigurator service in device image

### ISSUE THREAD

**Issue by bderuijsscher** [ms-iot/iot-core-azure-dm-client#231]
There seems to be a discrepancy in the explanation of how to properly implement the SystemConfigurator service within a test or retail image of a product.

The method mentioned in the documentation [(here)](https://github.com/ms-iot/iot-core-azure-dm-client/blob/master/docs/oem-device-setup.md), describes a method that involves adding the executable to the build manifest. Additionally, it states that a custom CMD file should be added that will install the SystemConfigurator as a service upon first boot. 

When reading the Core Manufacturing guide however [(here)](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/iot-core-adk-addons), there seems to be a package available that handles the installation, namely AzureDM.Services.  

It looks like the latter approach is desirable since it doesn't involve the requirement of a hardcoded administrator password.

**Comment by gmileka** [comment]
Thank you for reporting this discrepancy.
The iot-core-azure-dm-client documentation [here](https://github.com/ms-iot/iot-core-azure-dm-client/blob/master/docs/oem-device-setup.md) is pre-RS3.

For RS3 and later, the MSDN [documentation](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/iot-core-adk-addons) applies.

I will clarify the docs on GitHub to outline the difference.

Note however that the new way in adk-addons provides a "sample" implementation. The binaries provided in GitHub [here](https://github.com/ms-iot/iot-adk-addonkit/tree/master/Source-arm/Packages/AzureDM.Services) are not to be shipped. The user needs to build the binaries from source and include their own. AzureDM.Services is a privately built sample for demonstration purposes and to make following the lab easier. It should not be used in a production environment.

**Comment by gmileka** [comment]
Closing this.

The docs at https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/iot-core-adk-addons have been updated with a note to indicate the provided bits are just for testing:

*Note
The security packages contain test contents and you should replace them with your own device specific content when creating your final image. See Security, BitLocker and Deviceguard for more details.*
