### ISSUE TITLE
IoTDMBackground - Failure in SystemConfigurator SendRequest RPC code=1722

### ISSUE THREAD

**Issue by cmassman** [ms-iot/iot-core-azure-dm-client#233]
When I deploy to the RasPi I get these errors in the Output Window of Visual Studio.
Anyone know what might cause this?

Waiting...
Exception thrown: 'Microsoft.Devices.Management.Error' in IoTDMClient.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Waiting...
[AzureDM]    [Error]    Sub-system=DeviceManagement, code=1722, messag=Failure in SystemConfigurator SendRequest RPC
Sub-system=DeviceManagement, code=1722, messag=Failure in SystemConfigurator SendRequest RPC
Exception thrown: 'Microsoft.Devices.Management.Error' in IoTDMClient.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Waiting...
[AzureDM]    [Error]    Sub-system=DeviceManagement, code=1722, messag=Failure in SystemConfigurator SendRequest RPC
Sub-system=DeviceManagement, code=1722, messag=Failure in SystemConfigurator SendRequest RPC
Exception thrown: 'Microsoft.Devices.Management.Error' in IoTDMClient.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Waiting...

**Comment by cmassman** [comment]
I have made a little progress.   Now when I use the DM Dashboard to send a Reboot command to a device. It does update the device twin in Azure..
Watching the Output window when running the IoTDMBackground App it now detects the reboot command but gives me this error ...   The Output looks like this...

Executing direct method: windows.rebootAsync
[AzureDM]    [Verbose]    RebootCmdAsyncHandler() invoked by direct method.
[AzureDM]    [Verbose]    InternalRebootCmdAsync() invoked.
[AzureDM]    [Verbose]    InternalRebootCmdAsync(2018-02-16T11:59:58Z) invoked.
ReportPropertiesAsync...
[AzureDM]    [Information]    AzureIoTHubDeviceTwinProxy.ReportProperties
[AzureDM]    [Information]      Reporting: windows
[AzureDM]    [Information]        Reporting: rebootCmd
ReportPropertiesAsync...
[AzureDM]    [Information]    AzureIoTHubDeviceTwinProxy.ReportProperties
[AzureDM]    [Information]      Reporting: windows
[AzureDM]    [Information]        Reporting: rebootCmd
[AzureDM]    [Verbose]    IsRebootAllowedBySystem()
[AzureDM]    [Error]    Sub-system=DeviceManagement, code=1722, messag=Failure in SystemConfigurator SendRequest RPC
Sub-system=DeviceManagement, code=1722, messag=Failure in SystemConfigurator SendRequest RPC
Exception thrown: 'Microsoft.Devices.Management.Error' in IoTDMClient.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Devices.Management.Error' in System.Private.CoreLib.dll
[AzureDM]    [Error]    {"time":"2018-02-16T12:00:02.0123424-08:00","state":"failed","errSubSystem":"DeviceManagement","errCode":1722,"errContext":"Failure in SystemConfigurator SendRequest RPC"}
ReportPropertiesAsync...
[AzureDM]    [Information]    AzureIoTHubDeviceTwinProxy.ReportProperties
[AzureDM]    [Information]      Reporting: windows
[AzureDM]    [Information]        Reporting: rebootCmd
ReportPropertiesAsync...
[AzureDM]    [Information]    AzureIoTHubDeviceTwinProxy.ReportProperties
[AzureDM]    [Information]      Reporting: windows
[AzureDM]    [Information]        Reporting: rebootCmd

**Comment by cmassman** [comment]
I finally figured out how to get the SystemConfigurator.exe to Deploy and Install thru the buildimage command.  All is working now!

**Comment by tymtam2** [comment]
@cmassman On my system System Configurator is running, but I'm getting RPC code=1722.

Do you have any pointers?

**Comment by tymtam2** [comment]
All is good. I installed the service not on the system I was doing verification. Embarrassing, but true.
