### ISSUE TITLE
Failure in SystemConfigurator SendRequest RPC

### ISSUE THREAD

**Issue by JORGEGO** [ms-iot/iot-core-azure-dm-client#235]
Dear,
I am trying to reuse your solution IoTDMBackground, that it works perfectly, but when I moved to my solution, something I have forgotten that I receive the next message:

{{"errSubSystem":"DeviceManagement","errCode":5,"errContext":"Failure in SystemConfigurator SendRequest RPC"}}

When
![image](https://user-images.githubusercontent.com/3842104/36562229-a5d39cae-1816-11e8-9634-73175edfa670.png)

Thanks

**Comment by bfjelds** [comment]
How is your solution implemented?  Are you using a Background App of your own?  If you are, is that App declaring the SystemManagement capability in its appxmanifest like the sample [here](https://github.com/ms-iot/iot-core-azure-dm-client/blob/master/samples/IoTDMBackground/Package.appxmanifest)?

```
<iot:Capability Name="systemManagement" />
```

**Comment by gmileka** [comment]
Also, usually RPC errors indicate that the SystemConfigurator service is not running. Would be good to double check just in case.

**Comment by JORGEGO** [comment]
Thanks so much!! bfjelds your are right I have not included on the appxmanifest this capability. Now error has fixed.
