### ISSUE TITLE
[feature][customer] Accessing Write Filter functionality via Azure IoT hub

### ISSUE THREAD

**Issue by bderuijsscher** [ms-iot/iot-core-azure-dm-client#240]
According to several posts it is advised to protect the flash cards of devices running Windows IoT Core (e.g. Raspberry Pi) by enabling the Write Filter functionality. [This article outlines how that protection can be achieved](https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/unifiedwritefilter))

The article also states that the settings and status of the Write Filter can be accessed through MDM as they are exposed through the Write Filter CSP [(link)](https://docs.microsoft.com/nl-nl/windows/client-management/mdm/unifiedwritefilter-csp)

Is it currently possible to access the settings and status of the Write Filter through Azure IoT Hub/Device Twin properties? If not, is there a known timeframe for inclusion in the IoTDMClientLib?

**Comment by gmileka** [comment]
Hi bderuijsscher,

We haven't exposed the UnifiedWriterFilter CSP through the Azure DM client. We don't have plans to expose it in the near future (6 months). If needed, we can help give guidance and support on how to add it to the code (it'll be very similar to how other CSPs are exposed in in the Azure DM client).

**Comment by bderuijsscher** [comment]
Hi @gmileka ,
thanks for the reply, yes a little guidance would be appreciate so that we can determine the impact to implement this ourselves. 
Thanks in advance, regards

**Comment by gmileka** [comment]
Hi bderuijsscher,

Absolutely - we've added a walk-through document:
https://github.com/ms-iot/iot-core-azure-dm-client/blob/master/docs/exposing-new-configuration.md

Let me know if you have any questions...

**Comment by bderuijsscher** [comment]
Great, thanks!

**Comment by gmileka** [comment]
Moved to our internal work tracking system.
