### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by IotCore-Developer** [ms-iot/iot-core-azure-dm-client#244]
When I compile the code release ARM then I get following error when upgraded the solution to latest version 10.0.16299:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "?main@@YAHP$01$AAV?$Array@P$AAVString@Platform@@$00@Platform@@@Z" (?main@@YAHP$01$AAV?$Array@P$AAVString@Platform@@$00@Platform@@@Z)	ServiceConfiguratorProxyClientLib	F:\Temp\iot-core-azure-dm-client-master\src\SystemConfiguratorProxy\Client\vccorlib.lib(climain.obj)	1	

Any ideas ?

**Comment by gmileka** [comment]
This is unexpected... let me see if I can repro.

**Comment by gmileka** [comment]
When I moved ServiceConfiguratorProxyClientLib to 16299, I got the ARM for desktop error "Compiling Desktop applications for the ARM platform is not supported.".

I've added WindowsSDKDesktopARMSupport to the vcxproj, and that got me a clean build. So, I can't repro the same error you are seeing :(

Do you get an error if the project is built with 15063?

**Comment by IotCore-Developer** [comment]
I upgraded the whole solution because i need to be on version 16299.
Maybe thats the difference.

I dont have the other sdk’s installed so i can’t test your suggestion.

Did you only upgrade the proxy project or the whole solution ?

Sent from Mail for Windows 10

**Comment by gmileka** [comment]
Apologies for the late reply... I upgraded only the proxy project.

Let me try upgrading the whole solution.

**Comment by gmileka** [comment]
I've upgraded the solution to 16299, and I'm still not seeing the error (except the ARM error, of course).

Can you please upload the solution you have?

**Comment by IotCore-Developer** [comment]
This zip file contains an example of the problem:

https://1drv.ms/u/s!Ak4jMpDNcdoQgagP4F9cg9mw56K5pQ

**Comment by IotCore-Developer** [comment]
On a clean system, compilation for version 16299 finally worked!
