### ISSUE TITLE
Client reconnection issues when using MQTT

### ISSUE THREAD

**Issue by crates-barrels** [ms-iot/iot-core-azure-dm-client#245]
When using `TransportType.Mqtt` (which defaults to TCP), the device client will not resume connection after longer internet losses. However, when using `TransportType.Mqtt_WebSocket_Only` the connection will resume as expected.

**Steps to reproduce**

1. Use the [Hello world sample code](https://github.com/ms-iot/iot-core-azure-dm-client/blob/master/docs/dm-hello-world-coding.md)
2. Run the application with internet connected
3. Verify the device is connected by checking the `connectionState` = "connected" in the device twin
4. Disconnect the device from the internet
5. Wait for the device twin `connectionState` to become "disconnected"
6. Reconnect the device to the internet
7. The `connectionState` of the device will remain "disconnected" (expected result: "connected")

Now change the transport type to "MQTT websockets only" when creating the DeviceClient in `ResetConnectionAsync(DeviceClient existingConnection)`:
`TransportType.Mqtt` -> `TransportType.Mqtt_WebSocket_Only`
 
Follow the previous steps again and you will find the device client will reconnect after internet loss as expected.

**Traces**

MQTT:

> ResetConnectionAsync start
> ResetConnectionAsync end
> Connection changed: Disconnected_Retrying No_Network
> Connection changed: Disabled Client_Close

MQTT websockets only:

> ResetConnectionAsync start
> ResetConnectionAsync end
> Connection changed: Disconnected_Retrying No_Network
> Connection changed: Disconnected Retry_Expired
> Waiting for internet...
> Waiting for internet...
> /* SNIP */
> Waiting for internet...
> ResetConnectionAsync start
> existingClient.CloseAsync exception: One or more errors occurred. () 
> ResetConnectionAsync end

It seems to me the comment on line 82 of AzureIoTHubDeviceTwinProxy.cs is not always valid: the "No_Network" status does not lead to Retry_Expired when using MQTT TCP and should not be ignored.
If I use the same logic in the No_Network case as in Retry_Expired, the client reconnects as expected:
```
case ConnectionStatusChangeReason.No_Network:
    await InternalRefreshConnectionAsync();
    break;
```

This seems to fix the MQTT TCP reconnection, but might potentially break other protocols or situations.

**HockeyApp**

I also added HockeyApp to the application.
When reconnecting the device to the internet, I get a lot (~6 per minute) of these exceptions:
"A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ()".

> Exception Stack:
> 
> unknown location
> Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<CloseAsync>d__54.MoveNext()
> DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
> DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)

This is happening when using "MQTT" and "MQTT websockets only". So even when the device is connected again to the IoT Hub, the exceptions keep getting thrown.

**Versions**

UWP 10.0 build 16299
DM client commit [1e9d542](https://github.com/ms-iot/iot-core-azure-dm-client/commit/1e9d54252d4b628ab4e08a80725c24832773711a)

**Comment by gmileka** [comment]
Thanks for reporting this... I've just added the re-connection call to the No_Network status. I'll take a look at the second issue (repeatedly throwing an exception)...

**Comment by gmileka** [comment]
crates-barrels, the second issue seems to be an Azure SDK issue... could you please open an issue at https://github.com/Azure/azure-iot-sdk-csharp ?

**Comment by crates-barrels** [comment]
@gmileka Sure, thanks!
