### ISSUE TITLE
ACPITABL.DAT for Discrete TPM module in retail image not being used

### ISSUE THREAD

**Issue by bderuijsscher** [ms-iot/iot-core-azure-dm-client#247]
Hi,

after successfully building and testing the DM funtionality in a Test image, we've managed to build a retail image with the same SystemConfigurator package included. However, the service fails to start in a Retail mode imaged device, whereas it does start in a Test mode imaged device.

When powershelling into the retail imaged device, the systemconfigurator.exe binary is present however it doesn't provide any output when for example running systemconfigurator.exe -install 

We have retail signed the executable with a proper code signing certificate (using signbinaries command). 

Furthermore, we also attempted to build a Retail image with the IOT_DISABLE_UMCI and IOT_ENABLE_TESTSIGNING features (meant for testing purposes only). however to no avail.

Are there any other options to consider to determine why the executable fails to start?

**Comment by bderuijsscher** [comment]
As an addition: we have attempted to use the exact same featureset for building the image in Test mode when building the Retail mode image. However, still the SystemConfigurator doesn't seem to function properly only in the Retail imaged device.

**Comment by gmileka** [comment]
Can you try launching it under the debugger (windbg)?
You might want to turn-on loader snaps to be able to see what is taking place...
If the same binaries using on a test image are present, then it shouldn't be a missing dependency issue... but maybe something is still missing.

**Comment by bderuijsscher** [comment]
Hi, thanks for the advice. I am afraid that I’ll need a little more guidance as how to accomplish this. Thanks in advance

**Comment by crates-barrels** [comment]
@bderuijsscher, I had the same issue.
Did you include the CRT binaries in the retail image? It's in the "IOT_CRT140" feature.

**Comment by bderuijsscher** [comment]
Hi @crates-barrels ,

thanks for the headsup, for sake of testing I have now duplicated the functioning Test OEMinput.xml to the Retail XML with only omitting the IoTUAPNonProductionPartnerShareFM feature manifest. It now also includes the feature you mentioned.

The SystemConfigurator service appears to be running properly, however after further investigation through inclusion of the Urchin executables I have come to the conclusion that the ACPITABL.DAT required for the external discrete TPM module (by BuyZero as mentioned in the docs) is not being processed properly. Therefore, the Azure DM service will not startup properly. 

When reading the docs on this subject [(here)](https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/setuptpm) it appears that it requires us to enable test signing. However, this does not appear to be a viable or desired scenario for retail images.

Any clues on how to fix this?

Many thanks in advance.

**Comment by bderuijsscher** [comment]
I can confirm that, after adding the following line to the oemcustomization.cmd file in the initial boot section enables proper access to the TPM.

`bcdedit /set testsigning on`

However, I still doubt if this the correct route to take. Also, I have yet to test if this also works when using a proper stripped down version of the Retail Oem XML input file.

**Comment by gmileka** [comment]
Hi bderuijsscher,
Could you explain a little on how ACPITABL.DAT is being used? I might be able to reach out to folks who have experience on this...

**Comment by bderuijsscher** [comment]
Hi, I have followed the process outlined in the manual for setup of a discrete TPM module [here](https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/setuptpm#setup-discrete-tpm-dtpm). (specifically see step 4/5, in my case I would use the RPi2/SPI0_CS1/TISSPI-TPM20/ variant)

Again, in test mode (with testsigning probably on by default) it appears to function properly, in retail mode it does not without the bcdedit modification as I pointed out earlier.

**Comment by bderuijsscher** [comment]
Hello,

I did as much already in the Test built image. The Device Portal is not available in the retail image. To be clear, the process followed does function properly in the Test built image, it does NOT function when using the exact same approach for a Retail build. Again, it can be circumvented by utilizing the bcdedit command as mentioned above but this re-introduces allowance of test signing which is not desirable in a Retail image.

**Comment by mohandatla** [comment]
Thank you for trying out. Totally agreed with you for retail image test signing is not desirable. Could you please use limpet to install the acpitabl on it, for example open SSH and run limpet -lat
it shows you the list of ACPITABL's, try installing the above mentioned ACPITABL using limpet -iat 3 and let us know whether it is working or not. Before installing please delete if there is any existing ACPITABL.dat file.

**Comment by crates-barrels** [comment]
Hey bderuijsscher,
I'm not sure if you got any further here, but I noticed the built-in fTPM on the Dragonboard 410c will not work in retail images unless the RPMB is provisioned.
It seems you're using a different board (Raspberry Pi?), but perhaps it gives you a clue...

**Comment by bderuijsscher** [comment]
Hi crates-barrels,

thanks for response, what do you exactly mean with RPMB is provisioned? Indeed we are using the Raspberry PI 3 with an external TPM Module ([letstrust](https://letstrust.de/)). Mostly for the purpose of securely connecting the device to Azure IoT Hub, however the above mentioned advice by @mohandatla unfortunately didn't allow us to succeed. I suspect it relates to the mentioned DAT file somehow requiring a non-retail signed binary for it to access the TPM module.

Regards

**Comment by crates-barrels** [comment]
I unfortunately don't have experience using a discrete TPM on a Raspberry Pi.
The provisioning of the RPMB (replay protected memory block) is specifically for the Dragonboard 410c I believe. It is also needed for [Secure Boot and BitLocker to work correctly](https://github.com/ms-iot/iot-walkthrough/tree/master/Security).
But maybe on a Raspberry Pi, there is also another step you need to take in order for a TPM to start working.

**Comment by bderuijsscher** [comment]
Hi crates-barrels,

I appreciate your thoughts on this, maybe there is some love-hate relationship involved in the combination of Raspberry PI with a (trusted) Windows environment (as is stated quite clearly on [this](https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/securebootandbitlocker) page and for example in [this](https://social.msdn.microsoft.com/Forums/en-US/ba8c8821-b27a-4eec-afdf-10b06940dab4/bitlocker-device-encryption-on-rpi3-sd-card-clone-protection?forum=WindowsIoT) forum).

Unfortunately this leaves us only with an uncomfortable position of redesigning our required Ethernet based IoT solution to another imperfect solution based on lowcost hardware.

Thanks again for your advice, regards

**Comment by gmileka** [comment]
I'm closing this. Please, re-open if help is still needed.
