### ISSUE TITLE
Unhandled exception: The current user has already installed an unpackaged version of this app

### ISSUE THREAD

**Issue by tymtam2** [ms-iot/iot-core-azure-dm-client#253]
Test case: 

1. Run an application using Visual Studio in debugging mode.
2. Schedule an update via device twin
3. Results: the application, using the IoTDMClientLib requests the SystemConfigurator to install the new version, but the SystemConfiguator crashes.

Exception: The current user has already installed an unpackaged version of this app. A packaged version cannot replace this. The conflicting package is IoTToasterSample and it was published by (...)

**Comment by bderuijsscher** [comment]
Hello tymtam2, as far as I know it is not supported to install a packaged version of an application over an unpackaged (i.e. the one that is installed when debugging through VS) version. If you would like to test this update you'll need to prepare a packaged version of the first (old) version, then attempt an update with a newer version through the device twin/azure.

**Comment by tymtam2** [comment]
Hi bderuijsscher,

This issue is about the not handling the exception and an essential Device Management service stopping, not about the error message. 

In other words, expected behavior:
The service doesn't stop.

**Comment by bderuijsscher** [comment]
Hi tymtam2,

yes I am sorry, for some reason I manage to post my comment to the wrong issue. Thanks for reporting.

Regarding your comment, yes I have also experienced this an agree with you that the service should not crash.

**Comment by bderuijsscher** [comment]
Hello tymtam2,

sorry about that, I have also experienced this issue and agree that the service should not crash when this happens.

**Comment by gmileka** [comment]
I'll take a look - yes, the service should contain all such exceptions and report an error gracefully.

**Comment by gmileka** [comment]
I believe this has been fixed. I have tried repro'ing it with the latest bits where I threw an exception and SystemConfigurator was able to catch and report it correctly.
Please, re-open if you still see the problem.
