### ISSUE TITLE
SystemConfigurator.exe missing on app deploy

### ISSUE THREAD

**Issue by Jazzeroki** [ms-iot/iot-core-azure-dm-client#256]
Before I got deep into making any modifications to this code I wanted to get it running in it's vanilla state so I'm using a freshly downloaded copy with 0 modifications other that the debugger settings to connect to a Raspberry pi 3, not the B+ model as I understand that has driver issues.

I'm building and deploying the toaster app that loads an on the surface appears to work fine.

I'm following the instructions found here.
https://github.com/ms-iot/iot-core-azure-dm-client/blob/master/docs/samples.md

The problem I seem to be stuck on is 9. Verify that SystemConfigurator.exe is present:

The SystemConfiguratorProxyClient.dll and .winmd are present.  However the SystemConfigurator.exe itself is not.  And cannot be installed, stopped, started ect.  

I did however find the file in my debug folder for arm on my computer.

I guess my main question is how do I resolve it not being present?  Is there a missing project reference or a missing setting someone in one of my projects as to why that is not deploying with the rest of the app build?

Some additional sidenotes.
-I added the Virtual TPM to my installation of windows IoT core and in the azure connection string portion I put the url for my Azure device provisioning hub which is linked to my azure IoT hub.

-The Error that is being thrown is this "Failure in SystemConfigurator SendRequest RPC"

Windows  iot core version 10.0.17134.1

VS Enterprise 15.7.2

**Comment by bderuijsscher** [comment]
The error indicated indeed seems to point to the missing SystemConfigurator service, since the IotDMClientLib embedded in the Toaster App unsuccesfully attempts to contact that service through RPC.

I don't know exactly why the SystemConfigurator.exe is not being deployed to the RPI, however manually copying this executable from your local ARM build folder should be possible. For example, through SSH or Powershell. You would then be able to install and start the service as indicated in the documentation.

I always first verify if the service is up and running ( tlist or get-process in powershell ) before attempting to start the application that hosts the IoTDMClientLib.

**Comment by Jazzeroki** [comment]
Yeah I found some other instructions about how to copy over the systemconfigurator.exe install it and start it up.  

I was able to get it to work on one of my test raspberry pis.  I've installed it on my other test machines but now when I try to start the service I'm getting an error message reading.  

net : The service name is invalid.

the command I'm using is

net start systemconfigurator

I'm running it from powershell.

**Comment by bderuijsscher** [comment]
Hi Jazzeroki,

It appears as though the systemconfigurator is not installed properly, please verify this by running either Get-Process or Get-Service in powershell. You also might want to run SystemConfigurator.exe -install again to check if it installs successfully. It will provide you some output in the console when it is installed.

**Comment by Jazzeroki** [comment]
Ok, I figured out the issue.  Apparently running "SystemConfigurator.exe --install" will generate a message that makes it seems like it installed when in fact it hasn't.  A correct install will actually show a message saying correctly installed.  Also only use a single - before the word install.  Some of the instructions I saw in the docs showed using --install which is incorrect.
