### ISSUE TITLE
App on remote device not installing.

### ISSUE THREAD

**Issue by Jazzeroki** [ms-iot/iot-core-azure-dm-client#257]
I'm having an issue that apps that I set to install on my pi aren't installing.  I keep getting errors back from the pi about invalid directory, invalid container.  Everything else I've tried setting from the DM has worked so I'm not sure what I'm doing wrong.

I'm copying the snippets from the device twin that seem relevant.

        "apps": {
          "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0": {
            "pkgFamilyName": "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0",
            "version": "1.0.3.0",
            "startUp": "foreground",
            "appxSource": "https://visiblepsvappstorage.file.core.windows.net/piscanningtest1/PiScanningStation_1.0.3.0_x86_x64_arm.appxbundle",
            "depsSources": "https://visiblepsvappstorage.file.core.windows.net/piscanningtest1/Microsoft.NET.Native.Framework.2.1.appx",
            "certSource": "https://visiblepsvappstorage.file.core.windows.net/piscanningtest1/PiScanningStation_1.0.3.0_x86_x64_arm.cer",
            "certStore": "./Device/Vendor/MSFT/RootCATrustedCertificates/TrustedPeople"
          }

Here's another install request attempt

        "apps": {
          "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0": {
            "pkgFamilyName": "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0",
            "version": "1.0.3.0",
            "startUp": "foreground",
            "appxSource": "piscanningtest1/PiScanningStation_1.0.3.0_x86_x64_arm.appxbundle",
            "depsSources": "piscanningtest1/Microsoft.NET.Native.Framework.2.1.appx",
            "certSource": "piscanningtest1/PiScanningStation_1.0.3.0_x86_x64_arm.cer",
            "certStore": "./Device/Vendor/MSFT/RootCATrustedCertificates/TrustedPeople"
          }
        }

This is the result I usually see.

          "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0": {
            "pkgFamilyName": "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0",
            "version": "not installed",
            "startUp": "none",
            "installDate": "",
            "errorCode": -2147024773,
            "errorMessage": "The filename, directory name, or volume label syntax is incorrect.\r\n"

This is the connectiong string though I replace the sensitive bits with ?????

          "connectionString": "DefaultEndpointsProtocol=https;AccountName=visiblepsvappstorage;AccountKey=eD?????????????????????????92GJ/6+????????????????????????w==;EndpointSuffix=core.windows.net"

As a side note I have systemconfigurator installed and running.  I have the DMBackground client installed and running.

I have the azure url in the TPM on the device.

I have the connections strings for the IoT hub, and Azure storage service in the DM.

The FQDN attempt above was made by copying and pasting the links from azure storage for each of the individual bits.

**Comment by bderuijsscher** [comment]
Hi, I assume it has to do with the use of forward slashes, I have had the following device twin JSON that worked well for a software update:

```
{
"properties": {
    "desired" : {
      "windows": {
        "externalStorage": {
        "connectionString": "DefaultEndpointsProtocol=https;AccountName=?????;AccountKey=????==;EndpointSuffix=core.windows.net",
        },
        "apps" : {
            "?" : {
                "store" : true,
                "nonStore" : true,
            },
            "MyAPPIDHERE" : {
                "pkgFamilyName" : "MyAPPIDHERE",
                "version" : "1.3.6.0",
                "startUp" : "foreground",
                "appxSource" : "release\\MyAPPIDHERE.3.6.0_ARM.appx",
                "depsSources" : "release\\Microsoft.NET.Native.Framework.2.0.appx;release\\Microsoft.NET.Native.Runtime.2.0.appx;release\\Microsoft.VCLibs.ARM.14.00.appx",
                "certSource" : "release\\MyAPPIDHERE.3.6.0_ARM.cer",
                "certStore" : "./Device/Vendor/MSFT/RootCATrustedCertificates/TrustedPeople",
            }
        }
      }
    }
  }
}
```

**Comment by Jazzeroki** [comment]
Here's what I changed my install request in my device twin to look like.  And the response that I got.  I'm sure that this does work but there's some setting or setup step that I've missed.

        "apps": {
          "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0": {
            "pkgFamilyName": "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0",
            "version": "1.0.3.0",
            "startUp": "foreground",
            "appxSource": "piscanningtest1\\PiScanningStation_1.0.3.0_x86_x64_arm.appxbundle",
            "depsSources": "piscanningtest1\\Microsoft.NET.Native.Framework.2.1.appx;piscanningtest1\\Microsoft.NET.Native.Runtime.2.1.appx;piscanningtest1\\Microsoft.VCLibs.ARM.14.00.appx;",
            "certSource": "piscanningtest1\\piscanningtest1/PiScanningStation_1.0.3.0_x86_x64_arm.cer",
            "certStore": "./Device/Vendor/MSFT/RootCATrustedCertificates/TrustedPeople"
          }
        }
      },
      "$metadata": {
        "$lastUpdated": "2018-05-29T18:27:47.0223078Z",
        "$lastUpdatedVersion": 13,
        "windows": {
          "$lastUpdated": "2018-05-29T18:27:47.0223078Z",
          "$lastUpdatedVersion": 13
        }
      },
      "$version": 13
    },
    "reported": {
      "windows": {
        "apps": {
          "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0": {
            "pkgFamilyName": "3dde22bd-2099-43f3-a2e5-6c888d7c9f7a_fq8jsaapzhjf0",
            "version": "1.0.0.0",
            "startUp": "none",
            "installDate": "",
            "errorCode": -2146233088,
            "errorMessage": "The specified container does not exist."
          },

**Comment by Jazzeroki** [comment]
Yeah that does look erroneous.  

What really fixed my issue was related to this.

EndpointSuffix=core.windows.net"

It needed to be 

EndpointSuffix=file.core.windows.net"

The auto generated connection string for azure storage apparently doesn't default directly to the file storage option.  

@bderuijsscher Thanks for all the help
