### ISSUE TITLE
Usage and stability issues

### ISSUE THREAD

**Issue by Jazzeroki** [ms-iot/iot-core-azure-dm-client#258]
These are two relatively simple to fix issues so I'll list them in 1 issue here.

When switching from one device to another in the Applications tab the list of installed applications does not clear out and continues to show what was on the previously viewed device.

When adding connection strings for IoT hub, and Storage connection if invalid strings are pasted in and attempted to save it crashes the DM.

**Comment by gmileka** [comment]
Thx Jazzeroki - I've checked-in a couple of quick fixes for these two issues:

Clearing the app list: 7ab6b27cda03b80be9c00167a1bb00061022de97
Gracefully handle invalid connection strings: d5c132bb25182721c406c0cadf7d6152e3b10046
