### ISSUE TITLE
Build-in Azure Device Management service is crashing & freezing the Windows IoT core - SystemConfigurator.exe

### ISSUE THREAD

**Issue by majidshaffi** [ms-iot/iot-core-azure-dm-client#289]
**The SystemConfigurator.exe is crashing the Windows IoT core OS. Sometimes the OS recovers but sometimes requires a manual reboot.**

The behavior of system configurator service is persistent on Windows IoT Core 16299 as well as on 17134 builds.

•	The service is trying to use ucrtbase.dll from C:\windows\System32\ with an error code of 1000.
•	The service is crashing from the beginning of the windows bootup and continues to throw an error on the event log.
•	The service crash recovers itself but sometimes the windows need a manual re-start because of it.
•	The crash is happening on both versions of windows i.e. 16299 & 17134.

Important Information:

•	We are using the build in Azure DM service module that comes with the Add-on-Toolkit and packaging within the FFU. 
•	The service is installed and running under NT Authority\System account.

The error message is pasted below from the event logs:

**Faulting application name: SystemConfigurator.exe, version: 0.0.0.0, time stamp: 0x59ee665c
Faulting module name: ucrtbase.dll, version: 10.0.17134.1, time stamp: 0x793d7763
Exception code: 0xc0000409
Fault offset: 0x00051bab
Faulting process id: 0x160
Faulting application start time: 0x01d45fc4023f601c
Faulting application path: c:\Windows\System32\SystemConfigurator.exe
Faulting module path: C:\windows\System32\ucrtbase.dll
Report Id: 83860b40-c928-483b-8cc5-70ff6d0efd23
Faulting package full name: 
Faulting package-relative application ID:**

The screenshot of the error is pasted below:

![1](https://user-images.githubusercontent.com/40349849/46710990-b55c9a00-cc8d-11e8-87d3-662ddeee8faf.JPG)

Thanks

**Comment by tymtam2** [comment]
The crash report is:

Faulting application name: SystemConfigurator.exe, version: 0.0.0.0, time stamp: 0x59ee665c
Faulting module name: ucrtbase.dll, version: 10.0.16299.64, time stamp: 0xbbe3ea82
Exception code: 0xc0000409
Fault offset: 0x00051d6b
Faulting process id: 0x7ec
Faulting application start time: 0x01d45728f761267d
Faulting application path: c:\Windows\System32\SystemConfigurator.exe
Faulting module path: C:\windows\System32\ucrtbase.dll
Report Id: 2d2d0bd7-8ec7-4ff7-a15a-926ab4053d0b
Faulting package full name: 
Faulting package-relative application ID:

**Comment by gmileka** [comment]
The version of SystemConfigurator that comes with Add-on-Toolkit is out-dated. Please, use the latest sources on this repo in the master branch.
