### ISSUE TITLE
Several reported properties in "windowsUpdates" node always "<error>"

### ISSUE THREAD

**Issue by scout208** [ms-iot/iot-core-azure-dm-client#293]
My "windowsUpdates" node from the reported device twin looks like this:

```
"lastChange": {
    "time": "2018-11-15T23:08:43.7392091Z",
    "state": "completed"
  },
  "approved": "c7864ecb-f0d8-4fd7-97f6-6cff8ea27f33/7148f77c-1751-4e99-8344-868a5aad674c",
  "installed": "<error>",
  "failed": "<error>",
  "installable": "<error>",
  "pendingReboot": "<error>",
  "lastScanTime": "2018-11-15T21:47:04Z",
  "deferUpgrade": false
```

The `installed`, `failed`, `installable`, and `pendingReboot` properties are always `"<error>"`, making it difficult to debug windows update complications.

**Comment by gmileka** [comment]
Hi scout208, could you please follow the instructions [here](https://github.com/ms-iot/iot-core-azure-dm-client/blob/master/docs/debugging.md) to collect the logs?

**Comment by gmileka** [comment]
Closing for now. scout208, please, feel free to re-open if you still need help.
