### ISSUE TITLE
Will Holo lens is supported 

### ISSUE THREAD

**Issue by satish860** [ms-iot/iot-core-azure-dm-client#297]
Can the UWP app created for IOT core is deployable in Holo lens? The context behind the question as to how much we can reuse the device management code.

**Comment by gmileka** [comment]
Hi satish860,

It depends on what functionality you'll be accessing.

We can think of the Azure DM client as two main parts:

- Connectivity to Azure and routing. This part is generic and should run on HoloLens.
- Implementation of a specific configuration. 
    - In some cases, we rely on the Windows CSPs to apply a new configuration. For this to work on HoloLens, [Embedded Mode](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/embeddedmode) must be turned on.
    - In other cases, we rely on the underlying win32 apis. Those also should work on HoloLens unless the API is not available.

We do not test the Azure DM Client on HoloLens.

thanks,
george

**Comment by gmileka** [comment]
Please, re-open if you need further assistance.
