### ISSUE TITLE
Azure connection failure after Windows IoT Core update

### ISSUE THREAD

**Issue by bderuijsscher** [ms-iot/iot-core-azure-dm-client#302]
Since the Windows IoT core update last october, all our devices have lost their connection to the IoT hub.

After some investigation, we discovered that the Limpet component was excluded from that release. It previously was part of the base image. Since the DM client lib as implemented per the instructions depends on this component to be able to access the TPM, we need some way to re-install that component on our devices.

We are not sure how to proceed as we have no means of accessing / updating our devices in the field anymore.

Are there any suggestions?

Thanks in advance.

**Comment by gmileka** [comment]
Hi bderuijsscher,

For RS5+, Limpet.exe can be built and deployed from https://github.com/ms-iot/azure-client-tools .

We also recommend considering to move to the new Azure device agent in the same repo.

thanks,
george
