### ISSUE TITLE
DmClient app and other apps?

### ISSUE THREAD

**Issue by jezzsantos** [ms-iot/iot-core-azure-dm-client#305]
We have deployed a dedicated DmClient app (very close to the examples) and we use it specifically for helping us do over the air updates of our other app. It works great with SystemConfigurator.exe. We have tested this extensively and we are happy this scenario works for us.

However, both the DmClient app and the other app (that we deploy over the air) use the MQTT protocol.

We were seeing a tremendous amount of runtime errors when both apps are running on the same device at the same time. It took us a long time to find out that  only one connection can be made using MQTT from the same device.
Now, given that constraint. We have to resolve this issue. 

My question is now. that if we take DM code from the DmClient and include it in the code of the other app (the one that we deploy over the air), can we still update that app over the air in the same way as before? should that work?

**Comment by jezzsantos** [comment]
bump

**Comment by gmileka** [comment]
Hi jezzsantos,

Apologies for the late reply - we're also shifting our focus to our new [repo/client](https://github.com/ms-iot/azure-client-tools). Feel free to contact me directly at my email at microsoft.com (gmileka) for faster responses.

To answer your question, yes, this scenario is supported. You can upgrade the proxy UWP application. When the update information arrives, the dmclientlib will detect that it's update itself, and systemconfigurator will be able to re-launch it after the update is done.

The one connection per device identity was indeed a limitation. That's actually why we had this architecture where  a UWP application shares the connection with systemconfigurator. The UWP application should have the business logic, while it forwards the rest to systemconfigurator (through the dmclientlib) for device management.

With Azure IoT Hub introduction of [module twins](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-module-twins), multiple applications can now connect to an identity that can be tracked back to iot hub (each device on iot hub can have up to 20 sub modules).

We re-achitectured systemconfigure to make use of that features. The new repo/client makes use of modules to decouple the business app from device management.

thanks,
george
