### ISSUE TITLE
DeviceManagementClient creation failing with latest Microsoft.Azure.Devices.Client nuget

### ISSUE THREAD

**Issue by vepaduch** [ms-iot/iot-core-azure-dm-client#307]
We are currently using an UWP app which is dependent on both IoTDMClientLib and Microsoft.Azure.Devices.Client nuget packages. Recently we tried to update the Microsoft.Azure Devices.Client nuget version from 1.19.0 to 1.20.1 and we noticed that the below code is stuck in infinite loop(no progress after DeviceManagementClient.CreateAsync()  function call)

                _deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString,
                    new ITransportSettings[]
                    {
                        new AmqpTransportSettings(TransportType.Amqp_WebSocket_Only)
                        {
                            AmqpConnectionPoolSettings = new AmqpConnectionPoolSettings()
                            // TODO:Pooling is disabled due to issue in SDK and Windows update.
                            //{
                            //    Pooling = true,
                            //    MaxPoolSize = 100
                            //}
                        }
                    }
                    );
// IDeviceTwin abstracts away communication with the back-end.
                // AzureIoTHubDeviceTwinProxy is an implementation of Azure IoT Hub
                _deviceTwin = new AzureIoTHubDeviceTwinProxy(_deviceClient, _iotHubOfflineEvent, Logger.Log);
                _deviceClient.SetConnectionStatusChangesHandler(this.ConnectionChangeHandler);

                // IDeviceManagementRequestHandler handles device management-specific requests to the app,
                // such as whether it is OK to perform a reboot at any given moment, according the app business logic
                // ToasterDeviceManagementRequestHandler is the Toaster app implementation of the interface
                IDeviceManagementRequestHandler appRequestHandler = new DeviceManagementRequestHandler();

                // Create the DeviceManagementClient, the main entry point into device management
                this._dmClient = await DeviceManagementClient.CreateAsync(_deviceTwin, appRequestHandler);

Can some one please help us here in resolving this issue.

**Comment by gmileka** [comment]
We are taking a look now...

**Comment by gmileka** [comment]
Hi vepaduch,
I installed the latest bits from this repo and changed the Toaster application to use the latest Microsoft.Azure.Devices.Client and the ITransportSettings you've listed above. Such configuration worked for us, the device showed as connect, and we got past CreateAsync() and exited ResetConnectionAsync().

Can you repro the problem using the Toaster sample?

Also, when you say 'stuck in an infinite loop' - which loop is it?

Also, one way to collect more information is to collect debug logs:
https://github.com/ms-iot/iot-core-azure-dm-client/blob/master/docs/debugging.md

thanks,
george

**Comment by gmileka** [comment]
Worked with vepaduch - the problem here is the SDK's support for AMQP with  websockets:

<pre>
 var _deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString,
                    new ITransportSettings[]
                    {
                        new AmqpTransportSettings(TransportType.Amqp_WebSocket_Only)
                        {
                            AmqpConnectionPoolSettings = new AmqpConnectionPoolSettings()
                        }
                    }
                    );
</pre>

**Comment by gmileka** [comment]
see https://github.com/Azure/azure-iot-sdk-csharp/issues/949
