### ISSUE TITLE
Stop using naked Exceptions

### ISSUE THREAD

**Issue by arturl** [ms-iot/iot-core-azure-dm-client#34]
I see code like this in DM:

```
            if (result.Context != 0)
            {
                throw new Exception();
            }
```

Let's introduce a strong type for DM exceptions and put some useful info in it (error code might be OK, plus some text maybe)

**Comment by gmileka** [comment]
We now have DMException and DMExceptionWithErrorCode. Also, the information propagates all the way to the device twin now.
