### ISSUE TITLE
Deploying APPX without dependencies throws NULL.

### ISSUE THREAD

**Issue by sepple-ms** [ms-iot/iot-core-azure-dm-client#88]
AppxManagement.cs:
public async Task<string> AppInstallAsync(DeviceManagementClient client) { }

Missing NULL check on Dependencies. Should be like that:

var appInstallInfo = new AppInstallInfo();
                **if (null != Dependencies)
                {**
                    foreach (var dependencyBlobInfo in Dependencies)
                    {
                        var depPath = await dependencyBlobInfo.DownloadToTempAsync(client);
                        appInstallInfo.Dependencies.Add(depPath);
                    }
                **}**

**Comment by gmileka** [comment]
This should be by now (this part got re-written).
